services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5001"
  next:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
